CXX = g++
CXXFLAGS = -Wall -fPIC
LDFLAGS =
OBJFILES = ip_tree.o
TARGET_SHARED = libiptree.so
TARGET_STATIC = libiptree.a
OBJFILES_EXAMPLE = search_lib.o libiptree.a
TARGET_EXAMPLE = search_lib

all: $(TARGET_SHARED) $(TARGET_STATIC) $(TARGET_EXAMPLE)

$(TARGET_SHARED): $(OBJFILES)
	$(CXX) $(CXXFLAGS) -o $(TARGET_SHARED) $(OBJFILES) $(LDFLAGS) -shared

$(TARGET_STATIC): $(OBJFILES)
	ar -r $(TARGET_STATIC) $(OBJFILES)

$(TARGET_EXAMPLE): $(OBJFILES_EXAMPLE)
	$(CXX) $(CXXFLAGS) -o $(TARGET_EXAMPLE) $(OBJFILES_EXAMPLE) $(LDFLAGS)

clean:
	rm -f $(OBJFILES) $(TARGET_SHARED) $(TARGET_STATIC) $(TARGET_EXAMPLE) *~
